//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IFunctions")]
public interface IFunctions
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Verificare_existenta", ReplyAction="http://tempuri.org/InterfaceFunctions/Verificare_existentaResponse")]
    void Verificare_existenta();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Verificare_existenta", ReplyAction="http://tempuri.org/InterfaceFunctions/Verificare_existentaResponse")]
    System.Threading.Tasks.Task Verificare_existentaAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Update_proprietati", ReplyAction="http://tempuri.org/InterfaceFunctions/Update_proprietatiResponse")]
    void Update_proprietati(string path, string coloana, string valoare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Update_proprietati", ReplyAction="http://tempuri.org/InterfaceFunctions/Update_proprietatiResponse")]
    System.Threading.Tasks.Task Update_proprietatiAsync(string path, string coloana, string valoare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/stergere_poza", ReplyAction="http://tempuri.org/InterfaceFunctions/stergere_pozaResponse")]
    void stergere_poza(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/stergere_poza", ReplyAction="http://tempuri.org/InterfaceFunctions/stergere_pozaResponse")]
    System.Threading.Tasks.Task stergere_pozaAsync(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Tag", ReplyAction="http://tempuri.org/InterfaceFunctions/TagResponse")]
    void Tag(string path, string persoana);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Tag", ReplyAction="http://tempuri.org/InterfaceFunctions/TagResponse")]
    System.Threading.Tasks.Task TagAsync(string path, string persoana);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Add_Dinamic", ReplyAction="http://tempuri.org/InterfaceFunctions/Add_DinamicResponse")]
    void Add_Dinamic(string Nume);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Add_Dinamic", ReplyAction="http://tempuri.org/InterfaceFunctions/Add_DinamicResponse")]
    System.Threading.Tasks.Task Add_DinamicAsync(string Nume);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Afisare_persoane", ReplyAction="http://tempuri.org/InterfaceFunctions/Afisare_persoaneResponse")]
    string[] Afisare_persoane();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Afisare_persoane", ReplyAction="http://tempuri.org/InterfaceFunctions/Afisare_persoaneResponse")]
    System.Threading.Tasks.Task<string[]> Afisare_persoaneAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Afisare_Media", ReplyAction="http://tempuri.org/InterfaceFunctions/Afisare_MediaResponse")]
    string[] Afisare_Media();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Afisare_Media", ReplyAction="http://tempuri.org/InterfaceFunctions/Afisare_MediaResponse")]
    System.Threading.Tasks.Task<string[]> Afisare_MediaAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Scriere_in_fisier", ReplyAction="http://tempuri.org/InterfaceFunctions/Scriere_in_fisierResponse")]
    void Scriere_in_fisier(string path, string scris);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Scriere_in_fisier", ReplyAction="http://tempuri.org/InterfaceFunctions/Scriere_in_fisierResponse")]
    System.Threading.Tasks.Task Scriere_in_fisierAsync(string path, string scris);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Afisare_rezultate", ReplyAction="http://tempuri.org/InterfaceFunctions/Afisare_rezultateResponse")]
    string[] Afisare_rezultate(string coloana, string date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Afisare_rezultate", ReplyAction="http://tempuri.org/InterfaceFunctions/Afisare_rezultateResponse")]
    System.Threading.Tasks.Task<string[]> Afisare_rezultateAsync(string coloana, string date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Initializare_proprietati", ReplyAction="http://tempuri.org/InterfaceFunctions/Initializare_proprietatiResponse")]
    string[] Initializare_proprietati();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Initializare_proprietati", ReplyAction="http://tempuri.org/InterfaceFunctions/Initializare_proprietatiResponse")]
    System.Threading.Tasks.Task<string[]> Initializare_proprietatiAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Add_Media", ReplyAction="http://tempuri.org/InterfaceFunctions/Add_MediaResponse")]
    void Add_Media(string nume, string locatie, string path, string peisaj, string eveniment);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFunctions/Add_Media", ReplyAction="http://tempuri.org/InterfaceFunctions/Add_MediaResponse")]
    System.Threading.Tasks.Task Add_MediaAsync(string nume, string locatie, string path, string peisaj, string eveniment);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IFunctionsChannel : IFunctions, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class FunctionsClient : System.ServiceModel.ClientBase<IFunctions>, IFunctions
{
    
    public FunctionsClient()
    {
    }
    
    public FunctionsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public FunctionsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FunctionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FunctionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Verificare_existenta()
    {
        base.Channel.Verificare_existenta();
    }
    
    public System.Threading.Tasks.Task Verificare_existentaAsync()
    {
        return base.Channel.Verificare_existentaAsync();
    }
    
    public void Update_proprietati(string path, string coloana, string valoare)
    {
        base.Channel.Update_proprietati(path, coloana, valoare);
    }
    
    public System.Threading.Tasks.Task Update_proprietatiAsync(string path, string coloana, string valoare)
    {
        return base.Channel.Update_proprietatiAsync(path, coloana, valoare);
    }
    
    public void stergere_poza(string name)
    {
        base.Channel.stergere_poza(name);
    }
    
    public System.Threading.Tasks.Task stergere_pozaAsync(string name)
    {
        return base.Channel.stergere_pozaAsync(name);
    }
    
    public void Tag(string path, string persoana)
    {
        base.Channel.Tag(path, persoana);
    }
    
    public System.Threading.Tasks.Task TagAsync(string path, string persoana)
    {
        return base.Channel.TagAsync(path, persoana);
    }
    
    public void Add_Dinamic(string Nume)
    {
        base.Channel.Add_Dinamic(Nume);
    }
    
    public System.Threading.Tasks.Task Add_DinamicAsync(string Nume)
    {
        return base.Channel.Add_DinamicAsync(Nume);
    }
    
    public string[] Afisare_persoane()
    {
        return base.Channel.Afisare_persoane();
    }
    
    public System.Threading.Tasks.Task<string[]> Afisare_persoaneAsync()
    {
        return base.Channel.Afisare_persoaneAsync();
    }
    
    public string[] Afisare_Media()
    {
        return base.Channel.Afisare_Media();
    }
    
    public System.Threading.Tasks.Task<string[]> Afisare_MediaAsync()
    {
        return base.Channel.Afisare_MediaAsync();
    }
    
    public void Scriere_in_fisier(string path, string scris)
    {
        base.Channel.Scriere_in_fisier(path, scris);
    }
    
    public System.Threading.Tasks.Task Scriere_in_fisierAsync(string path, string scris)
    {
        return base.Channel.Scriere_in_fisierAsync(path, scris);
    }
    
    public string[] Afisare_rezultate(string coloana, string date)
    {
        return base.Channel.Afisare_rezultate(coloana, date);
    }
    
    public System.Threading.Tasks.Task<string[]> Afisare_rezultateAsync(string coloana, string date)
    {
        return base.Channel.Afisare_rezultateAsync(coloana, date);
    }
    
    public string[] Initializare_proprietati()
    {
        return base.Channel.Initializare_proprietati();
    }
    
    public System.Threading.Tasks.Task<string[]> Initializare_proprietatiAsync()
    {
        return base.Channel.Initializare_proprietatiAsync();
    }
    
    public void Add_Media(string nume, string locatie, string path, string peisaj, string eveniment)
    {
        base.Channel.Add_Media(nume, locatie, path, peisaj, eveniment);
    }
    
    public System.Threading.Tasks.Task Add_MediaAsync(string nume, string locatie, string path, string peisaj, string eveniment)
    {
        return base.Channel.Add_MediaAsync(nume, locatie, path, peisaj, eveniment);
    }
}
